### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by huihuimoe** [huihuimoe/one-page-scroll#2]
- [x] throttle `.goto` function

- [ ] handle scrollable content

- [ ] add more settings

- [x] #1 change ClassName

- [x] d.ts file

- [ ] unit test
